name: Continuous Deployment Github Pages workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Git Auth
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Git Config
        run: |
          git config --global user.email "cd-user@mk-moves.com"
          git config --global user.name "cd-user"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build -- --base=${{vars.BASE_URL}}
      - name: Deploy
        run: npm run deploy -- -r git@github.com:samdevega/lemoncode-module-seven-lab.git
      - name: Cleanup
        run: rm -r ~/.ssh